### ISSUE TITLE
image content not showing in browser

### ISSUE THREAD

**Issue by andzski** [vmware-tanzu/tanzu-dev-portal#773]
**What content are you providing feedback for?**

What piece of content are you providing feedback about?

**What can be improved?**

If this content fell short of your expectations, let us know what you had hoped would be included

**What's going well?**

If you enjoyed this content, let us know! 

**Is this content helpful?**

Overall, either as-is or with the suggested improvements, is this content helpful and useful?

**Comment by BrianMMcClain** [comment]
Hi @andzski, sorry to hear you're facing this issue. Can you provide a link to the page(s) that aren't working correctly for you? Additionally, do you mind sharing the OS and browser you're using? I skimmed through a few pages and I'm not able to reproduce this issue, so this info will help me nail down what's going on. Thanks!

**Comment by andzski** [comment]
![image](https://user-images.githubusercontent.com/13966498/116573432-c9635800-a8da-11eb-8a31-943ff6ecdd69.png)
![image](https://user-images.githubusercontent.com/13966498/116573476-d718dd80-a8da-11eb-82e4-bda22e0b1475.png)
Tried new browser, image link appears, but 404 error on content.

**Comment by BrianMMcClain** [comment]
Hi @andzski, this is actually expected, as where the image lives and how it's reference in the markdown is actually different than where it's stored in the repo. For example, the Markdown for that image embed is:

```
![2x2 diagram showing stickies in each quadrant](/images/practices/problem-prioritization/step-4.png)
```

Which is referencing where the image is stored on the built site: https://tanzu.vmware.com/developer/images/practices/problem-prioritization/step-4.png

Unfortunately this means that when the Markdown is rendered on GitHub when viewing the file, you'll see that the images are missing here, since the proper reference would be:

```
../../../static/images/practices/problem-prioritization/step-4.png
```

This is a downside to how the code is organized vs built, but the images do appear to be rendering on the live site properly, as shown below:

<img width="944" alt="Screen Shot 2021-04-29 at 4 25 31 PM" src="https://user-images.githubusercontent.com/1136557/116614738-51ac2200-a908-11eb-95eb-cd13ce0e2453.png">

If you're looking to make changes locally, one thing that I can suggest if you have Hugo and NPM installed, you can run the command `make preview` to build a local version of the site that will update as you make changes locally.
