### ISSUE TITLE
Alphabetize dictionary pre-commit hook in husky not always running?

### ISSUE THREAD

**Issue by bryanfriedman** [vmware-tanzu/tanzu-dev-portal#870]
For some reason, the husky pre-commit hook did not seem to run in this PR: https://github.com/vmware-tanzu/tanzu-dev-portal/pull/844

Do we need to add some instructions somewhere to ensure it is installed and runs successfully before build/commit?

**Comment by BrianMMcClain** [comment]
I know our initial thought was that pre-commit hooks aren't ran when using GitHub Desktop, though that doesn't seem to be the case. However, according to [this issue](https://github.com/desktop/desktop/issues/13112) it looks like there's a chance that perhaps due to the environment that they get ran, the hook may not have access to everything it needs to run it. Maybe need to add more debugging.

**Comment by bryanfriedman** [comment]
This is lo-pri and doesn't seem to happen very often.
